CREATE DEFINER=`achadosepedidos_staging`@`%` PROCEDURE `sp_count_total`()
BEGIN

declare SiglaUf varchar(2);
declare NomeNivelFederativo varchar(9);
declare NomePoder varchar(19);

drop temporary table if exists maps;

create temporary table maps as
select SiglaUf, NomeNivelFederativo, NomePoder;

insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AC', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AL', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AM', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AP', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('BA', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('CE', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('DF', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('ES', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('GO', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MA', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MG', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MS', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MT', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PA', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PB', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PE', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PI', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PR', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RJ', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RN', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RO', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RR', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RS', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SC', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SE', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SP', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('TO', 'Estadual', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AC', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AL', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AM', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AP', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('BA', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('CE', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('DF', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('ES', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('GO', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MA', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MG', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MS', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MT', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PA', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PB', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PE', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PI', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PR', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RJ', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RN', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RO', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RR', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RS', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SC', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SE', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SP', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('TO', 'Estadual', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AC', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AL', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AM', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AP', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('BA', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('CE', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('DF', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('ES', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('GO', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MA', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MG', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MS', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MT', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PA', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PB', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PE', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PI', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PR', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RJ', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RN', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RO', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RR', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RS', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SC', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SE', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SP', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('TO', 'Estadual', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AC', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AL', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AM', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AP', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('BA', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('CE', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('DF', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('ES', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('GO', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MA', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MG', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MS', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MT', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PA', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PB', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PE', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PI', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PR', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RJ', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RN', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RO', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RR', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RS', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SC', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SE', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SP', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('TO', 'Estadual', 'Ministério Público');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AC', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AL', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AM', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AP', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('BA', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('CE', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('DF', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('ES', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('GO', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MA', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MG', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MS', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MT', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PA', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PB', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PE', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PI', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PR', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RJ', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RN', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RO', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RR', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RS', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SC', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SE', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SP', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('TO', 'Estadual', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AC', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AL', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AM', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AP', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('BA', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('CE', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('DF', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('ES', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('GO', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MA', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MG', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MS', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MT', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PA', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PB', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PE', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PI', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PR', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RJ', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RN', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RO', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RR', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RS', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SC', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SE', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SP', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('TO', 'Municipal', 'Executivo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AC', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AL', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AM', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AP', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('BA', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('CE', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('DF', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('ES', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('GO', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MA', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MG', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MS', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MT', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PA', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PB', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PE', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PI', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PR', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RJ', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RN', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RO', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RR', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RS', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SC', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SE', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SP', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('TO', 'Municipal', 'Judiciário');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AC', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AL', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AM', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AP', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('BA', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('CE', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('DF', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('ES', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('GO', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MA', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MG', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MS', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MT', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PA', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PB', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PE', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PI', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PR', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RJ', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RN', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RO', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RR', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RS', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SC', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SE', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SP', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('TO', 'Municipal', 'Legislativo');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AC', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AL', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AM', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('AP', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('BA', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('CE', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('DF', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('ES', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('GO', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MA', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MG', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MS', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('MT', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PA', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PB', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PE', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PI', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('PR', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RJ', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RN', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RO', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RR', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('RS', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SC', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SE', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('SP', 'Municipal', 'Tribunais de Contas');
insert into maps (SiglaUf, NomeNivelFederativo, NomePoder) values ('TO', 'Municipal', 'Tribunais de Contas');

END
